//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkDemo1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.Helpers = new HashSet<Helper>();
        }
    
        public int Id { get; set; }
        public float Name { get; set; }
    
        public virtual ICollection<Helper> Helpers { get; set; }
    }
}
