//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkDemo1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Helper
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Purpose { get; set; }
        public int CourseId { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
